Caculator/Models/ErrorViewModel.cs
namespace Caculator.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Caculator/Models/MailInfo.cs
namespace Caculator.Models
{
    public class MailInfo
    {
        public string From
        {
            get;set;
        }
        public string To
        {
            get; set;
        }
        public string Subject { get; set; }
        public string Body { get; set; }
    }
}

Caculator/Controllers/CaculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Caculator.Controllers
{
    public class CaculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Calculate(double a = 0, double b = 0, char o = '+') 
        {
            switch (o)
            {
                case '+':
                    ViewBag.ketQua = a + b;
                    break;
                case '-':
                    ViewBag.ketQua = a - b;
                    break;
                case '*':
                    ViewBag.ketQua = a * b;
                    break;
                case ':':
                    ViewBag.ketQua = a / b;
                    break;
            }
            return View("Calculate");
        }
    }
}

Caculator/Controllers/EmailController.cs
using Caculator.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace Caculator.Controllers
{
    public class EmailController : Controller
    {
        private readonly IConfiguration _config;

        public EmailController(IConfiguration config)
        {
            _config = config;
        }

        public IActionResult Index()
        {
            return View("Send_Email");
        }
        public IActionResult Send_Email(MailInfo model)
        {
            var host = _config["MailSettings:Host"];
            var port = int.Parse(_config["MailSettings:Port"]);
            var user = _config["MailSettings:User"];
            var pass = _config["MailSettings:Password"];

            var mail = new SmtpClient(host,port)
            {
                Credentials = new NetworkCredential(user,pass),
                EnableSsl = true
            }; 

            //tạo email
            var message = new MailMessage();
            message.From = new MailAddress(model.From);
            message.ReplyToList.Add(model.From);
            message.To.Add(new MailAddress(model.To));
            message.Subject = model.Subject;
            message.Body = model.Body;

            //gửi mail
            mail.Send(message);
            return View();
        }
    }
}

Caculator/Controllers/HomeController.cs
using System.Diagnostics;
using Caculator.Models;
using Microsoft.AspNetCore.Mvc;

namespace Caculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Caculator/Controllers/UploadController.cs
using Grpc.Core;
using Microsoft.AspNetCore.Mvc;

namespace Caculator.Controllers
{
    public class UploadController : Controller
    {
        public IActionResult Index()
        {
            return View("UploadFiles");
        }
        public IActionResult UploadFiles(IFormFile image, IFormFile document)
        {
            if (document != null && document.Length > 0)
            {
                var uploadPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/UploadFiles");
                var filePath = Path.Combine(uploadPath, document.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    document.CopyTo(stream); // tương đương SaveAs(path)
                }

                if (image is { Length: > 0 })
                {
                    var imgPath = Path.Combine(uploadPath, image.FileName);
                    using var s1 = new FileStream(imgPath, FileMode.Create);
                    image.CopyTo(s1);

                    ViewBag.ImagePath = "/UploadFiles/" + image.FileName;
                    ViewBag.ImageType = image.ContentType;
                }

                ViewBag.filePath = "/UploadFiles/" + document.FileName;
                ViewBag.fileName = document.FileName;
                ViewBag.fileType = document.ContentType;
                ViewBag.fileSize = document.Length;
            }
            return View("UploadFiles");
        }
    }
}

Caculator/Views/Caculator/Calculate.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h2>Máy tính</h2>

<form asp-controller="Caculator" asp-action="Calculate" method="get">
    <div class="row">
    <div class="col-2">
        <label>Số A:</label> <br />
        <input type="number" name="a" />
    </div>
    
    <div class="col-1 text-center">
        <label>Phép toán:</label>
        <select name="o">
            <option value="+">+</option>
            <option value="-">-</option>
            <option value="*">*</option>
            <option value=":">:</option>
        </select>
    </div>

        <div class="col-2">
            <label>Số B:</label>
            <input type="number" name="b" />
        </div>

        <div class="col-1 text-center">
            <button class="btn btn-primary mt-3" type="submit">=</button>
        </div>
    
  
    
<div class="col-1 mt-3">
    @if (ViewBag.ketQua != null)
    {
        <h3>@ViewBag.ketQua</h3>
    }
        </div>
    </div>
</form>

Caculator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to my mini-project!</h1>
</div>

Caculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Caculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Caculator.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Caculator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caculator" asp-action="Calculate">Caculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="Index">Send-Email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Upload" asp-action="Index">Upload</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Caculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Caculator/Views/Upload/UploadFiles.cshtml
@{
    ViewData["Title"] = "UploadFiles";
}

<h1>Upload Files</h1>

<div class="row">
    <div class="col-3">
        <form asp-controller="Upload" asp-action="UploadFiles" method="post" enctype="multipart/form-data">
            <div>Hình ảnh</div>
            <input name="image" type="file" />
            @if (ViewBag.fileName != null){
            @if (ViewBag.ImageType.ToString().StartsWith("image"))
            {
                <img src="@ViewBag.ImagePath" alt="Uploaded Image" style="max-width:300px;" />
            }
            }
            <div>Tài liệu</div>
            <input name="document" type="file" />
            @if (ViewBag.fileName != null)
            {
                <h4>File detail</h4>
                <p>Tên: @ViewBag.fileName</p>
                <p>Loại: @ViewBag.fileType</p>
                <p>Kích thước: @ViewBag.fileSize bytes</p>
                <a href="@ViewBag.filePath" download>Tải file</a>
            }
            <hr />
            <input value="upload" type="submit" />
        </form>
    </div>
    <div class="col-3">
        
    </div>
</div>